name: Deploy Vite to GitHub Pages

on:
  # Trigger the workflow on pushes to the main branch
  push:
    branches: ["main"]

  # Allow manual triggering of the workflow
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job for the Vite app
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Upload `dist` folder to GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1  # Updated to v1
        with:
          path: ./dist  # Specify the folder to deploy (dist)

  # Deploy job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
